### PR TITLE
Add transformation C  12. Add @rendition="#right" for opener//dateline...

### PR DESCRIPTION
**Pull request by WaxCylinderRevival**
in order to update entire corpus to enhanced encoding practices

Related to: https://github.com/HistoryAtState/frus/pull/271

### CODE REVIEW

**Comment by joewiz** [comment]
@WaxCylinderRevival Looks good! I'll merge as soon as https://github.com/HistoryAtState/frus/pull/271 is merged.

**Comment by WaxCylinderRevival** [comment]
Great!  Thanks, @joewiz.

**Comment by WaxCylinderRevival** [comment]
Hi, @joewiz.  Could you please merge this pull request today or early next week?  We need the additional transformation and reordered steps for dates training.  

Note: This pull request can be merged before https://github.com/HistoryAtState/frus/pull/271 is approved as it doesn't relate to bracket conventions.

Thank you!

**Comment by WaxCylinderRevival** [comment]
Thank you, @joewiz!

**Comment by joewiz** [comment]
@WaxCylinderRevival Sure thing!

**Pull request merged**
